### PR TITLE
As part of the Pull Request Challenge, Minilla & Carton

### PR DESCRIPTION
**Pull request by jeturcotte**
So, I took your suggestion to heart, given that this originates from an orchestrated challenge, as this task involved trying a number of new things... pull requests, for example... but also minilla and carton I've never had opportunity or cause to try.  So far as I can tell, this works.  Apologies for any oversights.

### CODE REVIEW

**Comment by kablamo** [comment]
Cool.  Thanks for this.  I will try to get to this this week.

**Comment by jeturcotte** [comment]
No problem; it occurred to me after the fact that the cpanfile.snapshot
might have been better served in the .gitignore, but maybe not.  Still feel
like I overlooked something, but if you find out what it is, I'm all ears.

On Tue, Jan 27, 2015 at 1:06 PM, Eric Johnson notifications@github.com
wrote:

> Cool. Thanks for this. I will try to get to this this week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kablamo/MooseX-CachingProxy/pull/1#issuecomment-71696424
> .

## 

~jet

**Comment by kablamo** [comment]
@jeturcotte You were right to add cpanfile.snapshot to the repo.  Read `carton --help` if you are interested in the details.  

However `minil test` and `minil dist` should work but are failing atm.  I think the version numbers are not setup right?

**Comment by jeturcotte** [comment]
Right; I will poke at them this weekend

On Fri, Jan 30, 2015 at 8:23 PM, Eric Johnson notifications@github.com
wrote:

> @jeturcotte https://github.com/jeturcotte You were right to add
> cpanfile.snapshot to the repo. Read carton --help if you are interested
> in the details.
> 
> However minil test and minil dist should work but are failing atm. I
> think the version numbers are not setup right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kablamo/MooseX-CachingProxy/pull/1#issuecomment-72297592
> .

## 

~jet

**Comment by jeturcotte** [comment]
It's in better shape now; had to diminish my version of MooseX::Test::Role down to 0.02 from 0.06, and also fiddle with a little pod as it kept injecting complaints about those... but test and dist both appear happy.

**Comment by kablamo** [comment]
Nice work!  I really like Carton and Minilla.  I think minilla automatically added you to the META.json as a contributer too which is cool.  So your name should show up on the cpan page.

I might tweak a couple little things after, but this is good enough to merge.  I'm not sure why my synopsis is in the middle of the pod for example.  But thats not your fault.  That was me who wrote it that way.  And I will probably add travis and coveralls.

I really appreciate this pr, thanks!  :+1:

**Comment by kablamo** [comment]
Released.  You'll see your name on the right if you click the 'show them' link under contributers.

https://metacpan.org/pod/release/KABLAMO/MooseX-CachingProxy-0.002/lib/MooseX/CachingProxy.pm

**Comment by jeturcotte** [comment]
No problem; and yes, it's only natural that there'll be tweaks.  Travis is
something else I need to become familiar with at some point.  Anyhow,
cool... thanks again.  February challenge came in (another moose thing!)
and that individual is unresponsive, which complicates things a little
bit.  Have a good one!

On Mon, Feb 9, 2015 at 7:42 PM, Eric Johnson notifications@github.com
wrote:

> Released. You'll see your name on the right if you click the 'show them'
> link under contributers.
> 
> https://metacpan.org/pod/release/KABLAMO/MooseX-CachingProxy-0.002/lib/MooseX/CachingProxy.pm
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kablamo/MooseX-CachingProxy/pull/1#issuecomment-73622446
> .

## 

~jet

**Pull request merged**
